### ISSUE TITLE
 Error `require`ing adapter file  D:\my-promise\my-promise.js

### ISSUE THREAD

**Issue by Chorer** [promises-aplus/promises-tests#98]
I just implemented my own promise in the `my-promise.js` file. It just look like this:
```js
class MyPromise {
   ........
}
MyPromise.deferred = function () {
  var result = {};
  result.promise = new MyPromise(function (resolve, reject) {
    result.resolve = resolve;
    result.reject = reject;
  });

  return result;
}
module.exports = MyPromise
```
But after I have installed the promises-aplus-tests and run `promises-aplus-tests my-promises`. The cmd throws the error:
```ssh
PS D:\my-promise> promises-aplus-tests my-promise.js
D:\Node.js\node_global\node_modules\promises-aplus-tests\lib\cli.js:32
        throw error;
        ^

Error: Error `require`ing adapter file D:\my-promise\my-promise.js

SyntaxError: Unexpected token =
    at adapterObjectFromFilePath (D:\Node.js\node_global\node_modules\promises-aplus-tests\lib\cli.js:29:21)
    at Object.<anonymous> (D:\Node.js\node_global\node_modules\promises-aplus-tests\lib\cli.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```
I can't find the reason why this happened.

**Comment by Chorer** [comment]
sry it is just a syntax error.
